/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package blood.donation.symboisiss;

import java.util.Calendar;
import java.sql.Connection;
import java.sql.Date;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author CTG
 */
public class frame4 extends javax.swing.JFrame {

    String qry="";
    /**
     * Creates new form frame4
     */
    String bg="",area="";
    
    public frame4(String b, String a) {
        initComponents();
       bg=b;
        area=a;
 
        if (b.equals("Select Blood Group")) {
            qry="select ddID, ddName,ddGender,ddAge,ddBlood_group,ddContact,ddArea,ddLast_Date,ddRBC_donated,ddPlatelets_donated,ddWholeblooddonation from DONOR_DATA where ddArea='"+area+"' ";
        }
        else
        {
             qry="select ddID, ddName,ddGender,ddAge,ddBlood_group,ddContact,ddArea,ddLast_Date,ddRBC_donated,ddPlatelets_donated,ddWholeblooddonation from DONOR_DATA where ddArea='"+area+"'  and ddBlood_group='"+bg+"' ";
        }
       // System.out.println(b + " "+ a);
       displayall();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.setPreferredSize(new java.awt.Dimension(1200, 1000));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "NAME", "GENDER", "AGE", "BLOOD GROUP", "CONTACT", "AREA", "Title 7", "Title 8", "Title 9", "Title 10", "Title 11", "Title 12"
            }
        ));
        jTable1.setPreferredSize(new java.awt.Dimension(500, 64));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 102, 102));
        jLabel1.setText(" RESULTS OF REQUIRED SEARCH ARE AS FOLLOWS :-");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(95, 95, 95)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 323, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1174, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(715, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked

        int row=jTable1.getSelectedRow();
        int col=11;
        
       Calendar c= Calendar.getInstance();
       
       String dd = c.get(Calendar.DATE)+"/";
       int m =c.get(Calendar.MONTH);
       String mm="";
        if (m<10) {
             mm= "0"+m+"/";
        }
        else{
             mm= m+"/";
        }
        
       
       String yy = c.get(Calendar.YEAR)+"";
        
       
       
       
        dd = dd+mm+yy;
        
    Connection con=null;
    PreparedStatement ps=null;
    ResultSet rs=null;
    String id= (String) jTable1.getValueAt(row, 0);
    try{
        
        Class.forName("com.mysql.jdbc.Driver");
        con=DriverManager.getConnection("jdbc:mysql:///BLOOD_DONOR","root","1234");
        String qry ="update DONOR_DATA set ddLast_Date='"+dd+"' where ddID="+id+" ";
        ps=con.prepareStatement(qry);
        ps.executeUpdate();
        
        JOptionPane.showMessageDialog(rootPane, "Blood Donation done");
        displayall();
    }catch(Exception e)
            {
                System.out.println(e);
    }
        
       
       
    }//GEN-LAST:event_jTable1MouseClicked

  
    public void displayall()
{
         
    
    DefaultTableModel model=new DefaultTableModel();
    
    String cols[]={"ID","Name","Gender","Age","Blood Group","Contact","Area","Last Donation Date","Donate RBC","Donate Platelets","Donate Whole blood","Select Donor"};
    model.setColumnIdentifiers(cols);
    jTable1.setModel(model);
    
    Connection con=null;
    PreparedStatement ps=null;
    ResultSet rs=null;
    
    try{
        
        Class.forName("com.mysql.jdbc.Driver");
        con=DriverManager.getConnection("jdbc:mysql:///BLOOD_DONOR","root","1234");
        
    
        ps=con.prepareStatement(qry);
        rs=ps.executeQuery();
        
        while(rs.next())
        {
            String a=rs.getString("ddLast_date");
            
            char dd1=a.charAt(3);
            char dd2=a.charAt(4);
            
            if (dd1=='/') {
                dd1='0';
            }
            //System.out.println(dd1+" "+dd2);
            
            int mm=Integer.parseInt(dd1+""+dd2);
         
           // System.out.println(mm);
            java.util.Date d = new java.util.Date();
          int  mm1 = d.getMonth()+1;
         
         
            if ((mm) <= (mm1-3)) {
            String id=rs.getString("ddID");
            String red=rs.getString("ddRBC_donated");
            String plat=rs.getString("ddPlatelets_donated");
            String wb = rs.getString ("ddwholeblooddonation");
            Object name=rs.getString("ddName");
            Object gender=rs.getString("ddGender");
            Object age=rs.getString("ddAge");
            Object bloodgroup=rs.getString("ddBlood_Group");
            Object contact=rs.getString("ddContact");
            Object area=rs.getString("ddArea");
            
            Object data[]={id,name,gender,age,bloodgroup,contact,area,a,red,plat,wb,"Select"};
            
            
            model.addRow(data);
            
            jTable1.setModel(model);
            }
            
        }
        
        
    }catch(Exception e)
    {
        JOptionPane.showMessageDialog(rootPane, e);
                
    }
}
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frame4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frame4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frame4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frame4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frame4("","").setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
